-- 1). Display the number of days between system date and 1st January 2011 ? 
SELECT EXTRACT(DAY FROM (SYSDATE - CAST(TO_DATE('1.1.' || 2011, 'DD.MM.YYYY') AS TIMESTAMP ))) AS DAYS_BETWEEN_TWO_DATES FROM DUAL;
SELECT EXTRACT(DAY FROM SYSDATE - CAST(DATE '2011-01-01' AS TIMESTAMP)) AS DAYS_BETWEEN_TWO_DATES FROM DUAL;
SELECT SYSDATE - to_date('01-jan-2011') AS DAYS_BETWEEN_TWO_DATES FROM DUAL;

-- 2). Display how many employees joined in each month of the current year ?
SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;

SELECT HIRE_DATE, EXTRACT(MONTH FROM HIRE_DATE) AS HIRE_MONTH
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) = '2007' --EXTRACT(YEAR FROM SYSDATE)
ORDER BY HIRE_MONTH DESC;

SELECT EXTRACT(MONTH FROM HIRE_DATE) AS HIRE_MONTH, COUNT(EXTRACT(MONTH FROM HIRE_DATE)) AS COUNT_NEW_HIRES_PER_MONTH
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) = '2007' --EXTRACT(YEAR FROM SYSDATE)
GROUP BY EXTRACT(MONTH FROM HIRE_DATE)
ORDER BY HIRE_MONTH DESC;

SELECT TO_CHAR(HIRE_DATE,'MM') AS HIRE_MONTH, COUNT (*) AS NEW_HIRES_PER_MONTH
FROM EMPLOYEES 
WHERE TO_CHAR(HIRE_DATE,'YYYY')= '2007' --TO_CHAR(SYSDATE,'YYYY') 
GROUP BY TO_CHAR(HIRE_DATE,'MM')
ORDER BY HIRE_MONTH;

-- 3). Display manager ID and number of employees managed by the manager ?
SELECT e.EMPLOYEE_ID, e.MANAGER_ID
FROM EMPLOYEES e;

SELECT d.MANAGER_ID
FROM DEPARTMENTS d;

SELECT COUNT(e.EMPLOYEE_ID) AS EMPLOYEES_PER_MANAGER, e.MANAGER_ID AS SOLE_MANAGER
FROM EMPLOYEES e
GROUP BY e.MANAGER_ID
ORDER BY EMPLOYEES_PER_MANAGER DESC;

SELECT COUNT(e.EMPLOYEE_ID) AS EMPLOYEES_PER_MANAGER, e.MANAGER_ID AS SOLE_MANAGER
FROM EMPLOYEES e
INNER JOIN DEPARTMENTS d
ON e.EMPLOYEE_ID = d.MANAGER_ID
GROUP BY e.MANAGER_ID;

SELECT MANAGER_ID, COUNT(*) 
FROM EMPLOYEES 
GROUP BY MANAGER_ID;

-- 4). Display employee ID and the date on which he ended his previous job ? 
SELECT EMPLOYEE_ID, END_DATE 
FROM JOB_HISTORY
ORDER BY EMPLOYEE_ID;

SELECT EMPLOYEE_ID, MAX(END_DATE) 
FROM JOB_HISTORY 
GROUP BY EMPLOYEE_ID;

SELECT e.EMPLOYEE_ID, MAX(jh.END_DATE) AS END_DATE_OF_PREVIOUS_JOB
FROM EMPLOYEES e
INNER JOIN JOB_HISTORY jh
ON e.EMPLOYEE_ID = jh.EMPLOYEE_ID
GROUP BY e.EMPLOYEE_ID;

-- 5). Display number of employees joined after 15th of the month ?
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE EXTRACT(DAY FROM HIRE_DATE) > 15;

SELECT COUNT(*)
FROM EMPLOYEES
WHERE EXTRACT(DAY FROM HIRE_DATE) > 15;

SELECT COUNT(*) 
FROM EMPLOYEES 
WHERE TO_CHAR(HIRE_DATE,'DD') >= 15;
