-- 1). Display employees who joined in the month of May ?
SELECT TO_CHAR(HIRE_DATE,'MONTH') AS Hire_Date_Month  FROM EMPLOYEES;
SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'mon') = 'may';

-- 2). Display details of the employees where commission percentage is null and salary in the range 5000 to 10000 and department is 30 ?
DESC EMPLOYEES;
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, SALARY, COMMISSION_PCT, DEPARTMENT_ID 
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL
AND SALARY BETWEEN 5000 AND 10000
AND DEPARTMENT_ID = 30;

-- 3). Display first name and date of first salary of the employees ?
SELECT e.FIRST_NAME, e.LAST_NAME, jh.START_DATE
FROM EMPLOYEES e
INNER JOIN JOB_HISTORY jh
ON e.EMPLOYEE_ID = jh.EMPLOYEE_ID;

-- NOTE: LAST_DAY gets the last day of the month and people accordin to this database get paid on the first of the month, so plus one
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, LAST_DAY(HIRE_DATE)+1 AS FIRST_SALARY
FROM EMPLOYEES;

-- 4). Display first name and number of years experience of the employees ?

-- 'SYSDATE' gives todays date
SELECT SYSDATE FROM DUAL;

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, FLOOR((SYSDATE-HIRE_DATE)/365) AS NUMBER_OF_YEARS_EXPERIENCE FROM EMPLOYEES WHERE FIRST_NAME = 'Steven';

SELECT FIRST_NAME, HIRE_DATE, FLOOR((SYSDATE-HIRE_DATE)/365) AS NUMBER_OF_YEARS_EXPERIENCE
FROM EMPLOYEES;

SELECT FIRST_NAME, HIRE_DATE, FLOOR(MONTHS_BETWEEN(SYSDATE, HIRE_DATE ) / 12) AS NUMBER_OF_YEARS_EXPERIENCE
FROM EMPLOYEES;

-- 5). Display first name of employees who joined in 2001 ?
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 2001;

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN TO_DATE('1.1.' || 2001, 'DD.MM.YYYY')
AND TO_DATE('1.1.' || 2002, 'DD.MM.YYYY');

-- 6). Display first name and last name after converting the first letter of each name to upper case and the rest to lower case ?
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES;

SELECT INITCAP(FIRST_NAME), INITCAP(LAST_NAME) FROM EMPLOYEES;

-- 7). Display the first word in job title ?

-- All Mine
SELECT JOB_TITLE FROM JOBS;

SELECT JOB_TITLE, SUBSTR(JOB_TITLE, 1, REGEXP_INSTR(JOB_TITLE, ' ')) AS FIRST_WORD_IN_JOB_TITLE_COLUMN FROM JOBS;

SELECT JOB_TITLE, REGEXP_INSTR(JOB_TITLE, ' ') AS XXXXX FROM JOBS;
SELECT JOB_TITLE, INSTR(JOB_TITLE, ' ') AS XXXXX FROM JOBS;

SELECT JOB_TITLE, 
  (CASE WHEN REGEXP_INSTR(JOB_TITLE, ' ') = 0
    THEN JOB_TITLE
  ELSE SUBSTR(JOB_TITLE, 1, REGEXP_INSTR(JOB_TITLE, ' '))
  END) 
FROM JOBS;

-- Other guy
SELECT JOB_TITLE,  SUBSTR(JOB_TITLE,1, INSTR(JOB_TITLE, ' ')-1) FROM JOBS;

-- 8). Display the length of first name for employees where last name contain character ‘b’ after 3rd position ? 

-- Mine
SELECT FIRST_NAME, LENGTH(FIRST_NAME) AS LENGTH_OF_FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE UPPER(SUBSTR(LAST_NAME, 1, 3)) LIKE '%B%';

-- Other guy - NOT WORKING
SELECT FIRST_NAME, LAST_NAME 
FROM EMPLOYEES 
WHERE INSTR(LAST_NAME,'B') > 3;

-- 9). Display first name in upper case and email address in lower case for employees where the first name and email address are same irrespective of the case ?
SELECT UPPER(FIRST_NAME), LOWER(EMAIL) 
FROM EMPLOYEES
WHERE LOWER(FIRST_NAME) = LOWER(EMAIL);

SELECT UPPER(FIRST_NAME), LOWER(EMAIL) 
FROM EMPLOYEES 
WHERE UPPER(FIRST_NAME)= UPPER(EMAIL);

SELECT UPPER(FIRST_NAME), LOWER(EMAIL) 
FROM EMPLOYEES 
WHERE LOWER(FIRST_NAME) LIKE LOWER(EMAIL);

-- 10). Display employees who joined in the current year ?
SELECT TO_CHAR(SYSDATE, 'YYYY') FROM DUAL;
SELECT TRUNC(SYSDATE, 'YYYY') FROM DUAL;
SELECT EXTRACT(YEAR FROM sysdate) FROM DUAL;

SELECT FIRST_NAME, LAST_NAME, EMAIL, SALARY, JOB_ID
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) = EXTRACT(YEAR FROM SYSDATE);

SELECT FIRST_NAME, LAST_NAME, EMAIL, SALARY, JOB_ID 
FROM EMPLOYEES 
WHERE TO_CHAR(HIRE_DATE,'YYYY') = TO_CHAR(SYSDATE, 'YYYY');
